default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: music_listening

test:
  <<: *default
  database: music_listening

production:
  adapter: posgresql
  encoding: utf8
  pool: 5
  database: music_listening
  username: music_listening
  password: <%= ENV['PROJECTNAME_DATABASE_PASSWORD'] %>
